import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { StyledEngineProvider } from '@mui/material';
import { CustomizationStoreProvider } from '@/providers/customization-store-provider'
import CustomThemeProvider from "./customThemeProvider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Smart Mark App",
  description: "Generated by Rony with nextjs app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className="bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <StyledEngineProvider injectFirst>
            <CustomizationStoreProvider>
              <CustomThemeProvider>
                <Suspense>{children}</Suspense>
              </CustomThemeProvider>
            </CustomizationStoreProvider>
          </StyledEngineProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
